/**
 * Portfolio project data — single source of truth.
 * Visual sequence order is intentional.
 */
window.PORTFOLIO_PROJECTS = [
  {
    id: "01",
    slug: "smartads",
    name: "SmartAds LLC",
    category: "Advertising / Paid Media",
    country: "USA",
    year: "2026",
    url: "https://smartdigiads.com/",
    layout: "full",
    overview:
      "A focused digital experience created for a modern advertising and paid-media company, with a clear visual system and distinctive brand presentation.",
    role: ["Web Design", "Frontend Implementation", "Responsive Development"],
    deliverables: ["Responsive Website", "UI System", "Performance Pass"],
  },
  {
    id: "02",
    slug: "adsystemhaus",
    name: "Adsystemhaus GmbH",
    category: "Advertising / Paid Media",
    country: "Germany",
    year: "2026",
    url: "https://werbesystemhaus.com/",
    layout: "right-65",
    overview:
      "A refined web presence for a German advertising systems house, structured around clarity, hierarchy, and a restrained contemporary aesthetic.",
    role: ["Web Design", "Frontend Implementation", "Responsive Development"],
    deliverables: ["Responsive Website", "UI System", "Performance Pass"],
  },
  {
    id: "03",
    slug: "advisor-ad-service",
    name: "Advisor Ad Service LLP",
    category: "Advertising / Paid Media",
    country: "USA",
    year: "2026",
    url: "https://adserviceadvisor.com/",
    layout: "pair-left",
    overview:
      "An editorial digital experience for a performance-oriented advertising advisory practice, emphasizing system clarity and brand confidence.",
    role: ["Web Design", "Frontend Implementation", "Responsive Development"],
    deliverables: ["Responsive Website", "UI System", "Performance Pass"],
  },
  {
    id: "04",
    slug: "bbs",
    name: "BBS Werbeagentur GmbH",
    category: "Advertising / Creative Agency",
    country: "Germany",
    year: "2026",
    url: "https://bbswerbeexperten.com/",
    layout: "pair-right",
    overview:
      "A distinctive digital presentation for a German creative advertising agency, built around strong visual hierarchy and a precise brand voice.",
    role: ["Web Design", "Frontend Implementation", "Responsive Development"],
    deliverables: ["Responsive Website", "UI System", "Performance Pass"],
  },
  {
    id: "05",
    slug: "acm",
    name: "ACM – Werbeagentur GmbH",
    category: "Advertising / Creative Agency",
    country: "Germany",
    year: "2026",
    url: "https://acmonlinewerbung.com/",
    layout: "full",
    overview:
      "A structured website for a German advertising agency, designed to present services and identity with clarity and compositional restraint.",
    role: ["Web Design", "Frontend Implementation", "Responsive Development"],
    deliverables: ["Responsive Website", "UI System", "Performance Pass"],
  },
  {
    id: "06",
    slug: "ads-marketing-group",
    name: "ADS Marketing Group, LLC",
    category: "Advertising / Digital Marketing",
    country: "USA",
    year: "2026",
    url: "https://adsdigitalmarketing.com/",
    layout: "left-60",
    overview:
      "A digital marketing-focused website experience with a clear information architecture and a brand-forward visual system.",
    role: ["Web Design", "Frontend Implementation", "Responsive Development"],
    deliverables: ["Responsive Website", "UI System", "Performance Pass"],
  },
  {
    id: "07",
    slug: "ads-everywhere",
    name: "Ads Everywhere Inc.",
    category: "Advertising / Paid Media",
    country: "USA",
    year: "2026",
    url: "https://adseverywhereinc.com/",
    layout: "large",
    overview:
      "A contemporary digital presence for a paid-media advertising company, designed for strong first impressions and readable structure.",
    role: ["Web Design", "Frontend Implementation", "Responsive Development"],
    deliverables: ["Responsive Website", "UI System", "Performance Pass"],
  },
  {
    id: "08",
    slug: "ad-works",
    name: "AD Works LLC",
    category: "Advertising / Full-Service Agency",
    country: "USA",
    year: "2026",
    url: "https://adworksadvertising.com/",
    layout: "pair-left",
    overview:
      "A full-service advertising agency website built around photographic presence, confident typography, and a clear service narrative.",
    role: ["Web Design", "Frontend Implementation", "Responsive Development"],
    deliverables: ["Responsive Website", "UI System", "Performance Pass"],
  },
  {
    id: "09",
    slug: "ad-growth",
    name: "Ad Growth Inc.",
    category: "Advertising / Growth Media",
    country: "USA",
    year: "2026",
    url: "https://thegrowthplusads.com/",
    layout: "pair-right",
    overview:
      "A growth-oriented advertising brand site with a sharp visual system and a concise, conversion-aware landing experience.",
    role: ["Web Design", "Frontend Implementation", "Responsive Development"],
    deliverables: ["Responsive Website", "UI System", "Performance Pass"],
  },
  {
    id: "10",
    slug: "acc-advertising",
    name: "ACC Advertising Inc.",
    category: "Advertising / Paid Media",
    country: "USA",
    year: "2026",
    url: "https://accadvertisinginc.com/",
    layout: "oversized",
    overview:
      "A closing statement piece in the collection — a polished advertising brand website with measured pacing and a distinctive visual identity.",
    role: ["Web Design", "Frontend Implementation", "Responsive Development"],
    deliverables: ["Responsive Website", "UI System", "Performance Pass"],
  },
];

window.GEORGIAN_PROJECTS = [
  {
    id: "01",
    slug: "an-art-gallery",
    name: "Anart Gallery",
    tags: ["Gallery", "Web Design", "Responsive"],
    category: "Art / Gallery",
    country: "Georgia",
    url: "https://anartgallery.ge/",
    layout: "media-left",
    summary:
      "A refined digital presence for a Georgian art gallery — calm hierarchy, image-heavy layouts tuned for load speed, and a quiet luxury aesthetic.",
    meta: ["Frontend", "UI Refinement", "Performance"],
  },
  {
    id: "02",
    slug: "location-georgia",
    name: "Location Georgia",
    tags: ["Delivery", "Location Discovery", "Georgia"],
    category: "Delivery / Discovery",
    country: "Georgia",
    url: "https://location-georgia.netlify.app/",
    layout: "media-right",
    summary:
      "A location-discovery experience crafted for Georgian delivery — editorial pacing, clear destinations, and a cinematic visual tone.",
    meta: ["Frontend", "Web Design", "Responsive UI"],
  },
];
